### PR TITLE
ACAS-569: Fix for new line in quoted string

### PR DESCRIPTION
**Pull request by brianbolt**
## Description
 - Fix `Cannot read input csv file: EOF within quoted string` when uploading a csv file with new line characters in quoted strings.
 - This seems to break acasclient test `test_013_escaped_quotes_csv` specifically here:
https://github.com/mcneilco/acasclient/blob/a5528f215a3f0cdd1521fef4a11c23ab93eea664/tests/test_acasclient.py#L3804 I'll need to get clarification from @bffrost before merging this change.

## Related Issue
ACAS-569

## How Has This Been Tested?
Ran acas client tests.

### CODE REVIEW

**Review by dalejerikson — APPROVED** [review]
👍

**Review by bffrost — APPROVED** [review]
LGTM

**Comment by bffrost** [comment]
@brianbolt just to confirm, this is targeting 2022.4.x so it'll need to be upmerged

**Comment by brianbolt** [comment]
Yep. Thanks, I will upmerge

**Pull request merged**
